/*
 * This file is protected under the KILLGPL.
 * For more information visit <insert_valid_link_to_killgpl_here>
 * <p/>
 * Copyright (c) Luke A. Leber <LukeLeber@gmail.com> 2014
 */

package com.lukeleber.scandroid.sae.j1979;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

import static com.lukeleber.scandroid.sae.j1979.detail.AppendixB.*;

public class SAE_J1979
{


    public final static List<PID<? extends Serializable>> SAE_J1979_STATIC_PIDS
        = Arrays.asList(
            MONITOR_STATUS,
            FREEZE_FRAME_DTC,
            FUEL_SYSTEM_STATUS,
            CALCULATED_ENGINE_LOAD,
            ENGINE_COOLANT_TEMPERATURE,
            SHORT_TERM_FUEL_TRIM_BANK_1_3,
            LONG_TERM_FUEL_TRIM_BANK_1_3,
            SHORT_TERM_FUEL_TRIM_BANK_2_4,
            LONG_TERM_FUEL_TRIM_BANK_2_4,
            FUEL_RAIL_PRESSURE_NARROW_RANGE_ATMOSPHEREIC_REFERENCE,
            INTAKE_MANIFOLD_ABSOLUTE_PRESSURE,
            ENGINE_SPEED,
            VEHICLE_SPEED,
            TIMING_ADVANCE,
            INTAKE_AIR_TEMPERATURE,
            MASS_AIRFLOW_RATE,
            ABSOLUTE_THROTTLE_POSITION,
            SECONDARY_AIR_STATUS,
            DUAL_BANK_OXYGEN_SENSOR_LOCATIONS,
            DUAL_BANK_O2S11_CONVENTIONAL,
            QUAD_BANK_O2S11_CONVENTIONAL,
            DUAL_BANK_O2S12_CONVENTIONAL,
            QUAD_BANK_O2S12_CONVENTIONAL,
            DUAL_BANK_O2S13_CONVENTIONAL,
            QUAD_BANK_O2S21_CONVENTIONAL,
            DUAL_BANK_O2S14_CONVENTIONAL,
            QUAD_BANK_O2S22_CONVENTIONAL,
            DUAL_BANK_O2S21_CONVENTIONAL,
            QUAD_BANK_O2S31_CONVENTIONAL,
            DUAL_BANK_O2S22_CONVENTIONAL,
            QUAD_BANK_O2S32_CONVENTIONAL,
            DUAL_BANK_O2S23_CONVENTIONAL,
            QUAD_BANK_O2S41_CONVENTIONAL,
            DUAL_BANK_O2S24_CONVENTIONAL,
            QUAD_BANK_O2S42_CONVENTIONAL,
            OBD_SUPPORT,
            QUAD_BANK_OXYGEN_SENSOR_LOCATIONS,
            AUXILIARY_INPUT_STATUS,
            TIME_SINCE_ENGINE_START,
            DISTANCE_TRAVELLED_WHILE_MIL_IS_ACTIVATED,
            FUEL_RAIL_PRESSURE_RELATIVE_TO_MANIFOLD_VACUUM,
            FUEL_RAIL_PRESSURE_WIDE_RANGE,
            DUAL_BANK_O2S11_WIDE_RANGE,
            QUAD_BANK_O2S11_WIDE_RANGE,
            DUAL_BANK_O2S12_WIDE_RANGE,
            QUAD_BANK_O2S12_WIDE_RANGE,
            DUAL_BANK_O2S13_WIDE_RANGE,
            QUAD_BANK_O2S21_WIDE_RANGE,
            DUAL_BANK_O2S14_WIDE_RANGE,
            QUAD_BANK_O2S22_WIDE_RANGE,
            DUAL_BANK_O2S21_WIDE_RANGE,
            QUAD_BANK_O2S31_WIDE_RANGE,
            DUAL_BANK_O2S22_WIDE_RANGE,
            QUAD_BANK_O2S32_WIDE_RANGE,
            DUAL_BANK_O2S23_WIDE_RANGE,
            QUAD_BANK_O2S41_WIDE_RANGE,
            DUAL_BANK_O2S24_WIDE_RANGE,
            QUAD_BANK_O2S42_WIDE_RANGE,
            COMMANDED_EGR,
            EGR_ERROR,
            COMMANDED_EVAPORATIVE_PURGE,
            FUEL_LEVEL_INPUT,
            WARM_UPS_SINCE_DTC_RESET,
            DISTANCE_TRAVELLED_SINCE_DTC_RESET,
            EVAP_SYSTEM_VAPOR_PRESSURE,
            BAROMETRIC_PRESSURE,
            DUAL_BANK_O2S11_WIDE_RANGE_ALT,
            DUAL_BANK_O2S12_WIDE_RANGE_ALT,
            DUAL_BANK_O2S13_WIDE_RANGE_ALT,
            DUAL_BANK_O2S14_WIDE_RANGE_ALT,
            DUAL_BANK_O2S21_WIDE_RANGE_ALT,
            DUAL_BANK_O2S22_WIDE_RANGE_ALT,
            DUAL_BANK_O2S23_WIDE_RANGE_ALT,
            DUAL_BANK_O2S24_WIDE_RANGE_ALT,
            QUAD_BANK_O2S11_WIDE_RANGE_ALT,
            QUAD_BANK_O2S12_WIDE_RANGE_ALT,
            QUAD_BANK_O2S21_WIDE_RANGE_ALT,
            QUAD_BANK_O2S22_WIDE_RANGE_ALT,
            QUAD_BANK_O2S31_WIDE_RANGE_ALT,
            QUAD_BANK_O2S32_WIDE_RANGE_ALT,
            QUAD_BANK_O2S41_WIDE_RANGE_ALT,
            QUAD_BANK_O2S42_WIDE_RANGE_ALT,
            CATALYST_TEMPERATURE_BANK_1_SENSOR_1,
            CATALYST_TEMPERATURE_BANK_1_SENSOR_2,
            CATALYST_TEMPERATURE_BANK_2_SENSOR_1,
            CATALYST_TEMPERATURE_BANK_2_SENSOR_2,
            MONITOR_STATUS_THIS_DRIVING_CYCLE,
            CONTROL_MODULE_VOLTAGE,
            ABSOLUTE_LOAD_VALUE,
            COMMANDED_EQUIVALENCE_RATIO,
            RELATIVE_THROTTLE_POSITION,
            AMBIENT_AIR_TEMPERATURE,
            ABSOLUTE_THROTTLE_POSITION_B,
            ABSOLUTE_THROTTLE_POSITION_C,
            ABSOLUTE_THROTTLE_POSITION_D,
            ABSOLUTE_THROTTLE_POSITION_E,
            ABSOLUTE_THROTTLE_POSITION_F,
            COMMANDED_THROTTLE_ACTUATOR_CONTROL,
            MINUTES_RAN_BY_ENGINE_WITH_MIL_ACTIVATED,
            TIME_SINCE_DTC_CLEARED
        );
}